/* App config for images
 */
const images = {
  icons: {
    logo: require('../assets/icons/logo.png'),
    nav_logo: require('../assets/icons/nav-logo.png'),
    nav_account: require('../assets/icons/nav-account.png'),
    nav_back: require('../assets/icons/nav-back.png'),
    nav_close: require('../assets/icons/nav-close.png'),
    nav_notify: require('../assets/icons/nav-notify.png'),
    nav_order: require('../assets/icons/nav-order.png'),
    nav_qrcode: require('../assets/icons/nav-qrcode.png'),
    nav_cart: require('../assets/icons/nav-cart.png'),

    tab_home: require('../assets/icons/tab-home.png'),
    tab_menu: require('../assets/icons/tab-menu.png'),
    tab_promotion: require('../assets/icons/tab-promotion.png'),
    tab_store: require('../assets/icons/tab-store.png'),
    popup_close: require('../assets/icons/popup-close.png'),

    ic_text_jollibee: require('../assets/icons/ic-text-jollibee.png'),
    Walkthough1: require('../assets/icons/Walktrough1.png'),
    Walkthough2: require('../assets/icons/Walktrough2.png'),
    Walkthough3: require('../assets/icons/Walktrough3.png'),
    Walkthough4: require('../assets/icons/Walktrough4.png'),
    arrow_skip: require('../assets/icons/arrow-skip.png'),

    ic_jollibee: require('../assets/icons/ic-jollibee.png'),
    ic_promotion: require('../assets/icons/ic-promotion.png'),
    ic_address: require('../assets/icons/ic-address.png'),
    ic_arrow: require('../assets/icons/ic-arrow.png'),
    ic_notify: require('../assets/icons/ic-notify.png'),
    ic_order_list: require('../assets/icons/ic-orderlist.png'),
    ic_setting: require('../assets/icons/ic-setting.png'),
    ic_support: require('../assets/icons/ic-support.png'),

    ic_check_success: require('../assets/icons/ic-check-success.png'),
    ic_facebook: require('../assets/icons/ic-facebook.png'),
    ic_google: require('../assets/icons/ic-google.png'),
    ic_hide_password: require('../assets/icons/ic-hide-password.png'),
    ic_calendar: require('../assets/icons/ic-calendar.png'),
    ic_succeeded: require('../assets/icons/ic_succeeded.png'),
    ic_edit: require('../assets/icons/ic-edit.png'),
    ic_header_back: require('../assets/icons/ic-header-back.png'),
    ic_flag_vietnam: require('../assets/icons/ic-flag-vietnam.png'),
    ic_flag_english: require('../assets/icons/ic-flag-english.png'),
    ic_radio_active: require('../assets/icons/ic-radio-active.png'),
    ic_radio_inactive: require('../assets/icons/ic-radio-inactive.png'),
    ic_delete: require('../assets/icons/ic-delete.png'),
    ic_close_blur: require('../assets/icons/ic_close_blur.png'),
    ic_sub: require('../assets/icons/ic-sub.png'),
    ic_plus: require('../assets/icons/ic-plus.png'),
    ic_location: require('../assets/icons/ic-location.png'),

    ic_dropdown: require('../assets/icons/dropdown.png'),
    ic_order_edit: require('../assets/icons/ic-order-edit.png'),
    ic_store_address: require('../assets/icons/ic-store-home.png'),
    ic_store_phone: require('../assets/icons/ic-store-phone.png'),
    ic_store_clock: require('../assets/icons/ic-store-clock.png'),
    ic_pin_restaurant: require('../assets/icons/ic-pin-restaurant.png'),
    ic_order: require('../assets/icons/ic-order.png'),

    ic_qr_logo: require('../assets/icons/ic-qr-logo.png'),
    ic_delivery: require('../assets/icons/ic-delivery.png'),
    ic_in_store: require('../assets/icons/ic-in-store.png'),
    ic_money: require('../assets/icons/ic-money.png'),
    ic_sticked: require('../assets/icons/ic-sticked.png'),
    ic_use_tools: require('../assets/icons/ic-use-tools.png'),
    ic_arrow_down: require('../assets/icons/ic-arrow-down.png'),
    ic_arrow_up: require('../assets/icons/ic-arrow-up.png'),
    ic_order_phone: require('../assets/icons/ic-order-phone.png'),
    ic_order_text: require('../assets/icons/ic-order-text.png'),
    ic_send_chat: require('../assets/icons/ic-send-chat.png'),
    ic_popup_close_red: require('../assets/images/ic-popup-close-red.png'),
    ic_checked: require('../assets/icons/ic-checked.png'),

    tab_new_promotion: require('../assets/icons/tab-new-promotion.png'),
    tab_new_store: require('../assets/icons/tab-new-store.png'),
    tab_new_order: require('../assets/icons/tab-new-order.png'),
    tab_new_menu: require('../assets/icons/tab-new-menu.png'),

    ic_forward_red: require('../assets/icons/ic-forward-red.png'),
    ic_menu: require('../assets/icons/ic_menu.png'),
  },
  login_polygon: require('../assets/images/login-polygon.png'),
  menu_1: require('../assets/images/menu-gasot-chuacay.png'),
  menu_2: require('../assets/images/menu-ga-gion-vv.png'),
  menu_3: require('../assets/images/menu-mon-ngon.png'),
  menu_4: require('../assets/images/menu-mi.png'),
  menu_5: require('../assets/images/menu-mon-trang-mieng.png'),
  menu_6: require('../assets/images/menu-phan-an-phu.png'),
  menu_7: require('../assets/images/menu-burger-sandwich.png'),
  promotion_thumb: require('../assets/images/jollibee-promotion-thumb.png'),
  promotion_list_thumb: require('../assets/images/promotion-list-thumb.png'),
  jollibee_home: require('../assets/images/jollibee-home.png'),
  layout_white_home: require('../assets/images/layout-white-home.png'),
  jollibee_combo: require('../assets/images/jollibee-combo.png'),
  jollibee_combo1: require('../assets/images/jollibee-combo1.png'),
  jollibee_price: require('../assets/images/jollibee-price.png'),
  jollibee_news: require('../assets/images/jollibee-news.png'),
  item_detail_thumb: require('../assets/images/menu-item-detail-thumb.png'),
  menu_detail_item_pepsi: require('../assets/images/menu-detail-item-pepsi.png'),
  menu_detail_item_nuocsuoi: require('../assets/images/menu-detail-item-nuocsuoi.png'),
  bee_man: require('../assets/images/jollibee-wellcome-gift.gif'),
  jolibee_delivery: require('../assets/images/jolibee-delivery-gift.gif'),
  jolibee_cooking: require('../assets/images/jolibee-cooking-gift.gif'),
  jollibee_arrived: require('../assets/images/jollibee-arrived-gift.gif'),
  jollibee_like: require('../assets/images/jollibee-arrived.png'),
  jollibee_bubble: require('../assets/images/jollibee-bubble.png'),
  jollibee_bigorder: require('../assets/images/jollibee-bigorder.png'),
  bg_services: require('../assets/images/bg-services.png'),
  jollibee_cirlce_intro: require('../assets/images/jollibee-circle-intro.png'),
  jollibee_bg_intro: require('../assets/images/jollibee-bg-intro.png'),
  jollibee_driver_intro: require('../assets/images/jollibee-driver-intro.png'),
  jollibee_shop_intro: require('../assets/images/jollibee-shop.png'),
  jollibee_light_intro: require('../assets/images/jollibee-light-intro.png'),
  jollibee_gift_intro: require('../assets/images/jollibee-gift-intro.png'),
  watermark_background_2: require('../assets/images/watermark-background-2.png'),
  jollibee_head: require('../assets/images/jollibee-head.png'),
  jollibee_menu_mockup: require('../assets/images/Menu-Mockup.png'),
  jollibee_double_arrow: require('../assets/images/jollibee-double-arrow.png'),
  jollibee_arrow: require('../assets/images/jollibee-arrow.png'),
  loading_welcome: require('../assets/images/loading-welcome.gif'),
  watermark_background_transparent: require('../assets/images/watermark-background-transparent.png'),
  jollibee_background_new_home: require('../assets/images/jollibee-background-new-home.png'),
  jollibee_banners: require('../assets/images/jollibee-banners.png.png'),
  box_layout_tabs: require('../assets/images/box-layout-tabs.png'),
  jollibee_big_order: require('../assets/images/jollibee-big-order.png'),
  jollibee_birthday_order: require('../assets/images/jollibee-birthday-order.png'),
  bg_product_item: require('../assets/images/bg-product.png'),
};

export default images;
