require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native/scripts/react_native_pods'
rn_maps_path = '../node_modules/react-native-maps'
platform :ios, '10.0'

target 'loyalty' do
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])



  pod 'RNLocalize', :path => '../node_modules/react-native-localize'

  pod 'react-native-config', :path => '../node_modules/react-native-config'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'


  pod 'react-native-google-maps', :path => rn_maps_path
  pod 'GoogleMaps'
  pod 'Google-Maps-iOS-Utils'
  pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'

  pod 'CodePush', :path => '../node_modules/react-native-code-push'

  pod 'react-native-geolocation', :path => '../node_modules/@react-native-community/geolocation'

  target 'loyaltyTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)

  end

  target 'loyalty-develop' do
    inherit! :complete

  end
  target 'loyalty-staging' do
  end
end




