const ScreenName = {
  Main: 'Main',
  Welcome: 'Welcome',
  Account: 'Account',
  Splash: 'Splash',
  SignIn: 'SignIn',
  SignUp: 'SignUp',
  ForgotPassword: 'ForgotPassword',
  MenuDetail: 'MenuDetail',
  PromotionList: 'PromotionList',
  SettingAccount: 'SettingAccount',
  EditAccount: 'EditAccount',
  Reward: 'Reward',
  HistorySavedPoint: 'HistorySavedPoint',
  MySavedPoint: 'MySavedPoint',
  Support: 'Support',
  ChangeLanguage: 'ChangeLanguage',
  ChangePassword: 'ChangePassword',
  Notification: 'Notification',
  MenuItemDetail: 'MenuItemDetail',
  MyAddress: 'MyAddress',
  DetailMyAddress: 'DetailMyAddress',
  SearchAddress: 'SearchAddress',
  Order: 'Order',
  MyReward: 'MyReward',
};

export default ScreenName;
